# Generated by Django 5.2.3 on 2025-06-11 08:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("maze", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="maze",
            name="dead_ends",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
